#!/bin/bash

# Script to prepare project for Xcode Cloud building

echo "🌩️  Preparing Microverse for Xcode Cloud..."
echo ""
echo "Xcode Cloud can build your app without local Xcode!"
echo ""
echo "Steps:"
echo ""
echo "1. First, create an Apple Developer account (free):"
echo "   https://developer.apple.com/account"
echo ""
echo "2. Create a GitHub repository:"
echo "   https://github.com/new"
echo ""
echo "3. Push this project:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git remote add origin YOUR_GITHUB_URL"
echo "   git push -u origin main"
echo ""
echo "4. Sign in to App Store Connect:"
echo "   https://appstoreconnect.apple.com"
echo ""
echo "5. Go to Xcode Cloud and:"
echo "   - Click 'Create Workflow'"
echo "   - Connect your GitHub repo"
echo "   - Select 'Microverse' as the app"
echo "   - Choose 'Archive' action"
echo ""
echo "6. Xcode Cloud will build your app!"
echo "   Download the build from App Store Connect"
echo ""
echo "Press Enter to open the required websites..."
read

# Open helpful links
open "https://developer.apple.com/account"
open "https://github.com/new"
open "https://appstoreconnect.apple.com"
open "https://developer.apple.com/xcode-cloud/"