name: Microverse
options:
  bundleIdPrefix: com.microverse
  deploymentTarget:
    macOS: "11.0"
settings:
  CODE_SIGN_IDENTITY: ""
  CODE_SIGNING_REQUIRED: NO
  CODE_SIGN_ENTITLEMENTS: Microverse.entitlements
  PRODUCT_BUNDLE_IDENTIFIER: com.microverse.app
  INFOPLIST_FILE: Info.plist
  
targets:
  Microverse:
    type: application
    platform: macOS
    sources:
      - Sources
    settings:
      PRODUCT_NAME: Microverse
      MACOSX_DEPLOYMENT_TARGET: "11.0"
      SWIFT_VERSION: "5.0"
      ENABLE_HARDENED_RUNTIME: YES
